main: fr.alexandre1156.wardensrevolt.WardenRevolt
name: WardensRevolt
version: 0.1
authors: [Alexandre1156]
description: Mini-jeu basé sur Warden's Revolt par PetiteSilica (https://forum.epicube.fr/threads/wardens-revolt.124587/)